const Patient = require("../models/Patient");
const PatientInsight = require("../models/PatientInsight");
const { normalizeBatch } = require("../services/normalizerService");
const { generatePatientInsight } = require("../services/insightService");
const { generateAccessToken } = require("../services/accessTokenService");

// ─────────────────────────────────────────────
// POST /api/ingest
// ─────────────────────────────────────────────
const ingestPatients = async (req, res, next) => {
  try {
    const { patients, sourceHospital } = req.body;

    if (!patients || !Array.isArray(patients) || patients.length === 0) {
      return res.status(400).json({
        success: false,
        error: "Request body must contain a non-empty 'patients' array",
      });
    }

    const { results, errors } = normalizeBatch(patients, sourceHospital || "unknown");

    const saved = [];
    const skipped = [];

    for (const { unified, mappingLog, index } of results) {
      try {
        const patient = await Patient.findOneAndUpdate(
          { patientId: unified.patientId },
          { ...unified, insightGenerated: false },
          { upsert: true, new: true, runValidators: true }
        );

        saved.push({
          index,
          patientId: patient.patientId,
          name: patient.name,
          mappingLog,
        });
      } catch (dbErr) {
        skipped.push({ index, error: dbErr.message });
      }
    }

    return res.status(200).json({
      success: true,
      message: `Ingested ${saved.length} patients successfully`,
      saved,
      skipped,
      normalizationErrors: errors,
    });
  } catch (err) {
    next(err);
  }
};

// ─────────────────────────────────────────────
// POST /api/ingest/process
// ─────────────────────────────────────────────
const processPatients = async (req, res, next) => {
  try {
    const unprocessed = await Patient.find({ insightGenerated: false });

    if (unprocessed.length === 0) {
      return res.status(200).json({
        success: true,
        message: "No unprocessed patients found",
        results: [],
      });
    }

    const results = [];

    for (const patient of unprocessed) {
      const result = {
        patientId: patient.patientId,
        name: patient.name,
        insightGenerated: false,
        accessTokenCreated: false,
        error: null,
      };

      try {
        // Step 1: Generate AI insight
        const insightData = await generatePatientInsight(patient);

        // Step 2: Save insight
        await PatientInsight.findOneAndUpdate(
          { patientId: patient._id },
          { ...insightData, patientId: patient._id },
          { upsert: true, new: true }
        );

        result.insightGenerated = true;
        result.riskLevel = insightData.healthRiskIndicator?.level;
        result.riskScore = insightData.healthRiskIndicator?.score;

        // Step 3: Generate access token
        const accessToken = await generateAccessToken(patient._id);
        result.accessTokenCreated = true;
        result.accessLink = `${process.env.FRONTEND_URL}/report?token=${accessToken.token}`;
        result.tokenExpiresAt = accessToken.expiresAt;

        // Step 4: Simulate sending message to patient
        console.log("\n" + "=".repeat(60));
        console.log("📨 PATIENT MESSAGE SIMULATION");
        console.log("=".repeat(60));
        console.log(`To      : ${patient.name}`);
        console.log(`Phone   : ${patient.phone || "Not provided"}`);
        console.log(`Email   : ${patient.email || "Not provided"}`);
        console.log(`-`.repeat(60));
        console.log(`Message :`);
        console.log(`  Hello ${patient.name},`);
        console.log(`  Your health report has been generated by`);
        console.log(`  ${patient.sourceHospital || "your hospital"}.`);
        console.log(``);
        console.log(`  Risk Level : ${insightData.healthRiskIndicator?.level?.toUpperCase()}`);
        console.log(`  Risk Score : ${insightData.healthRiskIndicator?.score}/100`);
        console.log(``);
        console.log(`  Access your report here:`);
        console.log(`  ${result.accessLink}`);
        console.log(``);
        console.log(`  ⚠️  This link is accessible only once.`);
        console.log(`  Please download your report after viewing.`);
        console.log(`  Link expires on: ${new Date(accessToken.expiresAt).toDateString()}`);
        console.log("=".repeat(60) + "\n");

        // Step 5: Mark patient as processed
        await Patient.findByIdAndUpdate(patient._id, {
          insightGenerated: true,
          accessLinkSent: true,
        });
      } catch (err) {
        result.error = err.message;
        console.error(`❌ Failed to process ${patient.patientId}:`, err.message);
      }

      results.push(result);
    }

    const successCount = results.filter((r) => r.insightGenerated).length;

    return res.status(200).json({
      success: true,
      message: `Processed ${successCount}/${unprocessed.length} patients`,
      results,
    });
  } catch (err) {
    next(err);
  }
};

module.exports = { ingestPatients, processPatients };