"use client";

import { useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { useReport } from "@/context/ReportContext";

export default function ViewReportPage() {
  const router = useRouter();
  const { reportData, reset } = useReport();
  const printRef = useRef();

  // Redirect if no report data
  useEffect(() => {
    if (!reportData) {
      router.replace("/invalid");
    }
  }, [reportData, router]);

  if (!reportData) return null;

  const { patient, insight } = reportData;

  const getRiskColor = (level) => {
    switch (level) {
      case "low": return "text-green-400 bg-green-900/30 border-green-700/50";
      case "medium": return "text-yellow-400 bg-yellow-900/30 border-yellow-700/50";
      case "high": return "text-orange-400 bg-orange-900/30 border-orange-700/50";
      case "critical": return "text-red-400 bg-red-900/30 border-red-700/50";
      default: return "text-gray-400 bg-gray-900/30 border-gray-700/50";
    }
  };

  const getRiskEmoji = (level) => {
    switch (level) {
      case "low": return "🟢";
      case "medium": return "🟡";
      case "high": return "🟠";
      case "critical": return "🔴";
      default: return "⚪";
    }
  };

  const handleDownload = () => {
    window.print();
  };

  const handleExit = () => {
    reset();
    router.replace("/invalid");
  };

  return (
    <div className="min-h-screen bg-gray-950 py-8 px-4">
      <div ref={printRef} className="max-w-3xl mx-auto space-y-6">

        {/* ── Header ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white">🏥 Health Report</h1>
            <p className="text-gray-400 text-sm mt-1">
              Generated by APIE — Autonomous Patient Insight Engine
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleDownload}
              className="bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold py-2 px-4 rounded-xl transition-all"
            >
              📥 Download
            </button>
            <button
              onClick={handleExit}
              className="bg-gray-700 hover:bg-gray-600 text-white text-sm font-semibold py-2 px-4 rounded-xl transition-all"
            >
              🚪 Exit
            </button>
          </div>
        </div>

        {/* ── One Time Warning ── */}
        <div className="bg-yellow-900/30 border border-yellow-700/50 rounded-xl p-4">
          <p className="text-yellow-400 text-sm text-center">
            ⚠️ This link is accessible only once. Please download your report now.
          </p>
        </div>

        {/* ── Patient Info ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
          <h2 className="text-lg font-bold text-white mb-4">👤 Patient Information</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {[
              { label: "Name", value: patient.name },
              { label: "Age", value: patient.age ? `${patient.age} years` : "N/A" },
              { label: "Gender", value: patient.gender || "N/A" },
              { label: "Blood Group", value: patient.bloodGroup || "N/A" },
              { label: "Phone", value: patient.phone || "N/A" },
              { label: "Hospital", value: patient.sourceHospital || "N/A" },
            ].map((item) => (
              <div key={item.label} className="bg-gray-800 rounded-xl p-3">
                <p className="text-gray-500 text-xs mb-1">{item.label}</p>
                <p className="text-white text-sm font-semibold">{item.value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── Vitals ── */}
        {patient.vitals && (
          <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
            <h2 className="text-lg font-bold text-white mb-4">💓 Vitals</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: "Blood Pressure", value: patient.vitals.bloodPressure, unit: "mmHg" },
                { label: "Heart Rate", value: patient.vitals.heartRate, unit: "bpm" },
                { label: "Temperature", value: patient.vitals.temperature, unit: "°F" },
                { label: "Weight", value: patient.vitals.weight, unit: "kg" },
                { label: "Height", value: patient.vitals.height, unit: "cm" },
                { label: "BMI", value: patient.vitals.bmi, unit: "" },
                { label: "Blood Sugar", value: patient.vitals.bloodSugar, unit: "mg/dL" },
                { label: "SpO2", value: patient.vitals.oxygenSaturation, unit: "%" },
              ].map((v) => (
                <div key={v.label} className="bg-gray-800 rounded-xl p-3">
                  <p className="text-gray-500 text-xs mb-1">{v.label}</p>
                  <p className="text-white text-sm font-semibold">
                    {v.value ? `${v.value} ${v.unit}` : "N/A"}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Diagnoses, Medications, Allergies ── */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            { label: "🩺 Diagnoses", items: patient.diagnoses, color: "red" },
            { label: "💊 Medications", items: patient.medications, color: "blue" },
            { label: "⚠️ Allergies", items: patient.allergies, color: "yellow" },
          ].map((section) => (
            <div key={section.label} className="bg-gray-900 rounded-2xl p-5 border border-gray-800">
              <h2 className="text-sm font-bold text-white mb-3">{section.label}</h2>
              {section.items?.length > 0 ? (
                <ul className="space-y-2">
                  {section.items.map((item, i) => (
                    <li
                      key={i}
                      className={`text-xs px-3 py-2 rounded-lg bg-${section.color}-900/20 text-${section.color}-300 border border-${section.color}-800/30`}
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-gray-600 text-xs">None recorded</p>
              )}
            </div>
          ))}
        </div>

        {/* ── Risk Indicator ── */}
        <div className={`rounded-2xl p-6 border ${getRiskColor(insight.healthRiskIndicator?.level)}`}>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-bold">
              {getRiskEmoji(insight.healthRiskIndicator?.level)} Health Risk Indicator
            </h2>
            <span className="text-2xl font-bold">
              {insight.healthRiskIndicator?.score}/100
            </span>
          </div>

          {/* Risk Bar */}
          <div className="w-full bg-gray-800 rounded-full h-3 mb-4">
            <div
              className={`h-3 rounded-full transition-all duration-500 ${
                insight.healthRiskIndicator?.level === "low" ? "bg-green-500" :
                insight.healthRiskIndicator?.level === "medium" ? "bg-yellow-500" :
                insight.healthRiskIndicator?.level === "high" ? "bg-orange-500" :
                "bg-red-500"
              }`}
              style={{ width: `${insight.healthRiskIndicator?.score}%` }}
            />
          </div>

          <p className="text-sm font-semibold uppercase tracking-wider mb-3">
            Risk Level: {insight.healthRiskIndicator?.level}
          </p>

          {insight.healthRiskIndicator?.factors?.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {insight.healthRiskIndicator.factors.map((f, i) => (
                <span key={i} className="text-xs px-3 py-1 rounded-full bg-gray-800/50 border border-gray-700">
                  {f}
                </span>
              ))}
            </div>
          )}
        </div>

        {/* ── Summary ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
          <h2 className="text-lg font-bold text-white mb-3">📋 Clinical Summary</h2>
          <p className="text-gray-300 text-sm leading-relaxed">{insight.summary}</p>
        </div>

        {/* ── Warning Flags ── */}
        {insight.warningFlags?.length > 0 && (
          <div className="bg-red-900/20 rounded-2xl p-6 border border-red-800/40">
            <h2 className="text-lg font-bold text-red-400 mb-3">🚨 Warning Flags</h2>
            <ul className="space-y-2">
              {insight.warningFlags.map((flag, i) => (
                <li key={i} className="text-red-300 text-sm flex items-start gap-2">
                  <span>⚠️</span> {flag}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* ── Weekly Recommendations ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
          <h2 className="text-lg font-bold text-white mb-4">📅 Weekly Recommendations</h2>
          <div className="space-y-3">
            {insight.weeklyRecommendations?.map((item, i) => (
              <div key={i} className="flex gap-4 bg-gray-800 rounded-xl p-4">
                <span className="text-blue-400 font-bold text-sm w-24 shrink-0">{item.day}</span>
                <p className="text-gray-300 text-sm">{item.recommendation}</p>
              </div>
            ))}
          </div>
        </div>

        {/* ── General Recommendations ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
          <h2 className="text-lg font-bold text-white mb-4">💡 General Recommendations</h2>
          <ul className="space-y-2">
            {insight.generalRecommendations?.map((rec, i) => (
              <li key={i} className="text-gray-300 text-sm flex items-start gap-2">
                <span className="text-blue-400 mt-0.5">•</span> {rec}
              </li>
            ))}
          </ul>
        </div>

        {/* ── Diet & Exercise ── */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
            <h2 className="text-lg font-bold text-white mb-3">🥗 Dietary Advice</h2>
            <p className="text-gray-300 text-sm leading-relaxed">{insight.dietaryAdvice}</p>
          </div>
          <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800">
            <h2 className="text-lg font-bold text-white mb-3">🏃 Exercise Advice</h2>
            <p className="text-gray-300 text-sm leading-relaxed">{insight.exerciseAdvice}</p>
          </div>
        </div>

        {/* ── Medication Reminders ── */}
        {insight.medicationReminders?.length > 0 && (
          <div className="bg-blue-900/20 rounded-2xl p-6 border border-blue-800/40">
            <h2 className="text-lg font-bold text-blue-400 mb-4">💊 Medication Reminders</h2>
            <ul className="space-y-2">
              {insight.medicationReminders.map((reminder, i) => (
                <li key={i} className="text-blue-300 text-sm flex items-start gap-2">
                  <span>🔔</span> {reminder}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* ── Footer ── */}
        <div className="bg-gray-900 rounded-2xl p-6 border border-gray-800 text-center">
          <p className="text-gray-500 text-xs">
            Generated on {new Date(insight.generatedAt).toLocaleDateString("en-IN", {
              day: "numeric", month: "long", year: "numeric"
            })}
          </p>
          <p className="text-gray-600 text-xs mt-1">
            Powered by APIE — Autonomous Patient Insight Engine
          </p>
        </div>

      </div>
    </div>
  );
}